### PR TITLE
fix(docker): give PUID and PGID ownership of plugin files

### LINKED ISSUE #68: Dockermod causes jellyfin to crash due to config files ownership
### Describe the Bug

TLDR: The DOCKER_MOD installs the config dir and files with root ownership instead of the user that jellyfin runs as, causing jellyfin to crash on startup.

I have jellyfin running in a docker container on linux which has been working well for some time. I'm using the linuxserver/jellyfin image, along with their recommended `PUID` and `PGUID` options set to `1000`, and `UMASK_SET` of `022`.

Following the install docs, I added `DOCKER_MODS=lizardbyte/themerr-jellyfin:latest` to the environment variables in my `docker-compose.yaml` and issued a `docker-compose up -d`.

Examining the jellyfin logs reveals that the server repeatedly crashes due to an exception in the Themerr plugin with `System.UnauthorizedAccessException: Access to the path '/config/data/plugins/Themerr/meta.json' is denied.`

I noticed that the directory `/config/data/plugins/Themerr` and its files are all owned by `root` instead of the UID configured for the container, hence why the plugin is unable to access them once it starts up in jellyfin.

I manually chmod'd the files and everything fired up OK.

From looking at [the linuxserver s6 init scripts](https://github.com/linuxserver/docker-jellyfin/blob/master/root/etc/s6-overlay/s6-rc.d/init-jellyfin-config/run) I am guessing the fix would be to place an init script so that s6 changes ownership to the `abc` user on startup. Their own docker-mods docs don't seem to cover this situation, but maybe some other docker-mods out there have a simple solution.

It's likely this only happens if the mod is installed after jellyfin has already been initialised previously.

### Expected Behavior

The jellyfin server should start and begin answering network requests instead of crashing.

### Additional Context

Complete cycle from the logfile - this pattern repeats as docker restarts the container:
```
jellyfin_1   | [22:59:28] [INF] [1] Main: Jellyfin version: 10.8.10
jellyfin_1   | [22:59:28] [INF] [1] Main: Environment Variables: ["[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_PublishedServerUrl, https://XXXXXXXXXXX/]", "[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_DATA_DIR, /config/data]"]
jellyfin_1   | [22:59:28] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
jellyfin_1   | [22:59:28] [INF] [1] Main: Operating system: Linux
jellyfin_1   | [22:59:28] [INF] [1] Main: Architecture: X64
jellyfin_1   | [22:59:28] [INF] [1] Main: 64-Bit Process: True
jellyfin_1   | [22:59:28] [INF] [1] Main: User Interactive: True
jellyfin_1   | [22:59:28] [INF] [1] Main: Processor count: 32
jellyfin_1   | [22:59:28] [INF] [1] Main: Program data path: /config/data
jellyfin_1   | [22:59:28] [INF] [1] Main: Web resources path: /usr/share/jellyfin/web
jellyfin_1   | [22:59:28] [INF] [1] Main: Application directory: /usr/lib/jellyfin/bin/
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /config/cache
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bookshelf, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Bookshelf_9.0.0.0/Jellyfin.Plugin.Bookshelf.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.CoverArtArchive, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Cover Art Archive_7.0.0.0/Jellyfin.Plugin.CoverArtArchive.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MetaBrainz.Common.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021 from /config/data/plugins/Cover Art Archive_7.0.0.0/MetaBrainz.Common.Json.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MetaBrainz.MusicBrainz.CoverArt, Version=4.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021 from /config/data/plugins/Cover Art Archive_7.0.0.0/MetaBrainz.MusicBrainz.CoverArt.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Fanart, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Fanart_10.0.0.0/Jellyfin.Plugin.Fanart.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Opds, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/OPDS_4.0.0.0/Jellyfin.Plugin.Opds.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=19.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Open Subtitles_19.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Themerr, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Themerr/Jellyfin.Plugin.Themerr.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly YoutubeExplode, Version=6.2.5.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Themerr/YoutubeExplode.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Tvdb, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_10.0.0.0/Jellyfin.Plugin.Tvdb.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TheTVDB_10.0.0.0/TvDbSharper.dll
jellyfin_1   | [22:59:29] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TMDb Box Sets_10.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll
jellyfin_1   | [22:59:29] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [192.168.0.0/16,10.0.0.0/8]
jellyfin_1   | [22:59:29] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
jellyfin_1   | [22:59:29] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [192.168.0.0/16,10.0.0.0/8]
jellyfin_1   | [22:59:29] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
jellyfin_1   | [22:59:29] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
jellyfin_1   | [22:59:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bookshelf 9.0.0.0
jellyfin_1   | [22:59:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Cover Art Archive 7.0.0.0
jellyfin_1   | [22:59:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Fanart 10.0.0.0
jellyfin_1   | [22:59:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OPDS Feed 4.0.0.0
jellyfin_1   | [22:59:40] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Open Subtitles 19.0.0.0
jellyfin_1   | [22:59:40] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error creating Jellyfin.Plugin.Themerr.Plugin
jellyfin_1   | System.UnauthorizedAccessException: Access to the path '/config/data/plugins/Themerr/meta.json' is denied.
jellyfin_1   |  ---> System.IO.IOException: Permission denied
jellyfin_1   |    --- End of inner exception stack trace ---
jellyfin_1   |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin_1   |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin_1   |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_1   |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_1   |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin_1   |    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
jellyfin_1   |    at System.IO.File.WriteAllText(String path, String contents)
jellyfin_1   |    at Emby.Server.Implementations.Plugins.PluginManager.SaveManifest(PluginManifest manifest, String path)
jellyfin_1   |    at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
jellyfin_1   | [22:59:40] [FTL] [1] Main: Error while starting server.
jellyfin_1   | System.UnauthorizedAccessException: Access to the path '/config/data/plugins/Themerr/meta.json' is denied.
jellyfin_1   |  ---> System.IO.IOException: Permission denied
jellyfin_1   |    --- End of inner exception stack trace ---
jellyfin_1   |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin_1   |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin_1   |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_1   |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin_1   |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin_1   |    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
jellyfin_1   |    at System.IO.File.WriteAllText(String path, String contents)
jellyfin_1   |    at Emby.Server.Implementations.Plugins.PluginManager.SaveManifest(PluginManifest manifest, String path)
jellyfin_1   |    at Emby.Server.Implementations.Plugins.PluginManager.ChangePluginState(LocalPlugin plugin, PluginStatus state)
jellyfin_1   |    at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
jellyfin_1   |    at Emby.Server.Implementations.ApplicationHost.<>c__DisplayClass99_0`1.<GetExports>b__0(Type i)
jellyfin_1   |    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
jellyfin_1   |    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
jellyfin_1   |    at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
jellyfin_1   |    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
jellyfin_1   |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
jellyfin_1   |    at Emby.Server.Implementations.ApplicationHost.GetExports[T](CreationDelegateFactory defaultFunc, Boolean manageLifetime)
jellyfin_1   |    at Emby.Server.Implementations.Plugins.PluginManager.CreatePlugins()
jellyfin_1   |    at Emby.Server.Implementations.ApplicationHost.FindParts()
jellyfin_1   |    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
jellyfin_1   |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin_1   | [22:59:40] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
jellyfin_1   | [22:59:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
jellyfin_1   | [22:59:40] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

This PR fixes an issue where Jellyfin would crash during initialization if the user specified a PUID and/or PGID.

Additionally, unpins dependencies in buildstage as they change too often.

### Issues Fixed or Closed

- Fixes #68 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

File: dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-universal-themerr-jellyfin/run.sh [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+║          Themerr-jellyfin, a LizardByte application           ║
+║                                                               ║
+║  Docs: https://docs.lizardbyte.dev/projects/themerr-jellyfin  ║
+║      Support center: https://app.lizardbyte.dev/#Support      ║
+║          Donate: https://app.lizardbyte.dev/#Donate           ║
+║                                                               ║
+╚═══════════════════════════════════════════════════════════════╝
+'
+
+lsiown abc:abc /config/data/plugins/themerr-jellyfin
```
Comment (agittins) [inline dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-universal-themerr-jellyfin/run.sh:21]: I think the plug-in is capitalised and doesn't have the `-jellyfin` suffix, but I'm only on my phone at the moment.
```suggestion
lsiown abc:abc /config/data/plugins/Themerr
```

**Review by agittins — COMMENTED** [review]
The approach looks good to me, without any real experience with s6 myself, though. That file path is the only thing I can see that might need checking.

File: dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-universal-themerr-jellyfin/run.sh (hunk 1 above)
Comment (ReenigneArcher) [reply dockermod_root/etc/s6-overlay/s6-rc.d/init-mod-universal-themerr-jellyfin/run.sh:21]: Cool, thanks for the review! The path is correct. It's set near the end of the Dockerfile.

```dockerfile
# variables
ARG PLUGIN_NAME="themerr-jellyfin"
ARG PLUGIN_DIR="/config/data/plugins"

# add files from buildstage
# trailing slash on artifacts directory copies the contents of the directory, instead of the directory itself
COPY --link --from=buildstage /artifacts/ $PLUGIN_DIR/$PLUGIN_NAME
```
